### ISSUE TITLE
Failing to Properly parse title of Google Docs json.

### ISSUE THREAD

**Issue by Boilingtub** [g1mv/jsonic#2]
When parsing json from google docs , 

expected output :
{
    "title": "Document Title",
    "body":    {
        ⋮
    },
    "document Style":  {
        ⋮
    },
   ⋮
}

found output :
{
    3&"V,
    "body":    {
        ⋮
    },
    "document Style":  {
        ⋮
    },
   ⋮
}

This only happend to the title field , which is the first field to appear in the json data
the title is a random length , random characters string.

steps to recreate :

```
~ fn parse_doc(raw_json: String) -> JsonItem {
~      let json = match jsonic::parse(raw_json.as_str()) {
~           Ok(v) => v,
~           Err(e) => {
~                 println!("error parsing document `{}`",e);
~                 panic!("could not parse document json in Document::new(raw_json:&str)");
~             },
~     };
~ }
          ⋮
~ let doc_json = parse_doc(doc_plain_text);
~ let doc_json_str = doc_json.as_str().unwrap();
~ println!("\n\ndoc_json_str = [\n{{\n{}\n}}\n",doc_json_str);
```

attached is the exact json I am trying to parse in the `example.txt` file

[example.txt](https://github.com/user-attachments/files/16265270/example.txt)

I apologize in advance, if the odd behaviour is due to a mistake on my side.

**Comment by g1mv** [comment]
Hello, thanks for your report! I'll have a look at this shortly.

**Comment by g1mv** [comment]
I tried the code below, according to your message:

```
use std::fs::read_to_string;

use jsonic::json_item::JsonItem;

fn parse_doc(raw_json: String) -> JsonItem {
    let json = match jsonic::parse(raw_json.as_str()) {
        Ok(v) => v,
        Err(e) => {
            println!("error parsing document `{}`", e);
            panic!("could not parse document json in Document::new(raw_json:&str)");
        }
    };
    json
}

fn main() {
    let doc_plain_text = read_to_string("./example.txt").unwrap();
    let doc_json = parse_doc(doc_plain_text);
    let doc_json_str = doc_json.as_str().unwrap();
    println!("\n\ndoc_json_str = [\n{{\n{}\n}}\n", doc_json_str);
}
```

However on my side and with the latest release (v0.2.12), I'm not able to reproduce, the output exactly matches the input, as expected. Can you try it on your side?

**Comment by Boilingtub** [comment]
I will try it as soon as possible

**Comment by Boilingtub** [comment]
No , for me the same error persists.

Top of output :

doc_json_str = [
{
 #P #P,
  "body": {
    "content": [
      {
        "endIndex": 1,
        "sectionBreak": {
          "sectionStyle": {
            "columnSeparatorStyle": "NONE",
            "contentDirection": "LEFT_TO_RIGHT",
            "sectionType": "CONTINUOUS"
          }
        }
      },

the title is #P #P, instead of "title" : "Push_Doc Test Doc",

it might be a "my computer" specifically issue.
I am using
OS: Void Linux x86_64
Kernel: 6.6.42_1
Shell: bash 5.2.21
Terminal: foot
CPU: Intel i5-1035G1 (8) at 3.6GHz

the odd thing is that it is only the title that has this odd behaviour , I
am currently using a work around by copying the title out before hand then
parsing and replacing the title back in.

if there is any other information I can provide to help, please let me know

**Comment by g1mv** [comment]
It could also be a display problem on your side (something in relation with your terminal maybe?). To clear this out, could you please try the following code and see if you get an error?

```
use std::fs::read_to_string;

use jsonic::json_item::JsonItem;

fn parse_doc(raw_json: String) -> JsonItem {
    let json = match jsonic::parse(raw_json.as_str()) {
        Ok(v) => v,
        Err(e) => {
            println!("error parsing document `{}`", e);
            panic!("could not parse document json in Document::new(raw_json:&str)");
        }
    };
    json
}

fn main() {
    let doc_plain_text = read_to_string("./example.txt").unwrap();
    let doc_json = parse_doc(doc_plain_text);
    assert_eq!(doc_json["title"].as_str(), Some("Push_Doc Test Doc"));
}
```

**Comment by Boilingtub** [comment]
I will try this as soon as possible.

**Comment by Boilingtub** [comment]
When running the code you provide,
I get the output :

assertion `left == right` failed
  left: None
 right: Some("Push_Doc Test Doc")

I am using jsonic = "0.2.12"

**Comment by g1mv** [comment]
Are you using the exact same example.txt file you uploaded earlier, i.e. this one: [example.txt](https://github.com/user-attachments/files/16508851/example.txt) ?

**Comment by Boilingtub** [comment]
I was using that exact example.txt file, to make sure I just now downloaded
and ran with the file you just sent. And i still get the exact same output.

assertion `left == right` failed
  left: None
 right: Some("Push_Doc Test Doc")

could there possibly be a difference in the version of the rust compiler we
use ?
i am using rustc 1.80.0 (051478957 2024-07-21)

**Comment by g1mv** [comment]
I'm on rustc 1.80.0 (051478957 2024-07-21)... but I also tested the library with earlier rust versions without encountering problems.

Can you try, just to make sure that nothing has been tampered with (by the system/software etc.) and we are using byte-to-byte identical data:
```bash
shasum example.txt
```
And report your hash?

**Comment by Boilingtub** [comment]
This is the Hash for the example.txt on my side:

4b7dc02a84af1f275a0740889e45598390bbf49c  example.txt

**Comment by g1mv** [comment]
Yes, same there.
It's a difficult one, as I'm unable to reproduce the problem. It could have something to do with character encoding, but

* std::fs::read_to_string checks if input is correct UTF-8
* rust works with UTF-8 strings internally on all platforms, so there should be no difference in how the algorithms operate from one platform to another

so I'm not convinced. Although I'm pretty sure it won't make any difference, did you try with the latest rust version 1.80.1 (3f5fd8dd4 2024-08-06)?
